# Generated by Django 2.2.4 on 2020-09-28 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nazwa strony')),
                ('slug', models.SlugField(unique=True, verbose_name='Nazwa strony')),
                ('date_published', models.DateTimeField()),
                ('name_1', models.CharField(max_length=11)),
                ('name_2', models.CharField(max_length=11)),
                ('name_3', models.CharField(max_length=11)),
                ('section_footer_row_2', models.BooleanField(default=True)),
                ('section_footer_row_3', models.BooleanField(default=True)),
                ('add_navbar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Add')),
                ('basic_center_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_center_1', to='app.Article')),
                ('basic_center_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_center_2', to='app.Add')),
                ('large_basic_under', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='large_basic_under', to='app.Article')),
                ('navbar_alert_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navbar_alert_1', to='app.Article')),
                ('navbar_alert_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navbar_alert_2', to='app.Article')),
                ('navbar_alert_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navbar_alert_3', to='app.Article')),
                ('navbar_alert_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navbar_alert_4', to='app.Article')),
                ('navbar_alert_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navbar_alert_5', to='app.Article')),
                ('section_footer_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_footer_1', to='app.Article')),
                ('section_footer_10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_footer_10', to='app.Add')),
                ('section_footer_11', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_footer_11', to='app.Article')),
                ('section_footer_12', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_footer_12', to='app.Add')),
                ('section_footer_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_footer_2', to='app.Add')),
                ('section_footer_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_footer_3', to='app.Article')),
                ('section_footer_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_footer_4', to='app.Add')),
                ('section_footer_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_footer_5', to='app.Article')),
                ('section_footer_6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_footer_6', to='app.Article')),
                ('section_footer_7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_footer_7', to='app.Add')),
                ('section_footer_8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_footer_8', to='app.Article')),
                ('section_footer_9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_footer_9', to='app.Article')),
                ('section_second_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_second_1', to='app.Article')),
                ('section_second_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_second_2', to='app.Add')),
                ('section_second_left_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_second_left_1', to='app.Add')),
                ('section_second_left_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_second_left_2', to='app.Article')),
                ('section_second_left_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_second_left_3', to='app.Article')),
                ('section_second_left_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_second_left_4', to='app.Article')),
                ('section_second_left_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_second_left_5', to='app.Add')),
                ('slider_lg_basic_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_lg_basic_1', to='app.Article')),
                ('slider_lg_basic_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_lg_basic_2', to='app.Article')),
                ('slider_lg_basic_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_lg_basic_3', to='app.Article')),
                ('slider_lg_basic_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_lg_basic_4', to='app.Article')),
                ('slider_lg_basic_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_lg_basic_5', to='app.Article')),
                ('slider_lg_basic_6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_lg_basic_6', to='app.Article')),
                ('slider_lg_basic_7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_lg_basic_7', to='app.Article')),
                ('slider_lg_basic_8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_lg_basic_8', to='app.Article')),
                ('slider_lg_basic_9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_lg_basic_9', to='app.Article')),
                ('slider_sm_basic_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_sm_basic_1', to='app.Article')),
                ('slider_sm_basic_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_sm_basic_2', to='app.Article')),
                ('slider_sm_basic_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_sm_basic_3', to='app.Article')),
                ('slider_sm_basic_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_sm_basic_4', to='app.Article')),
                ('slider_sm_basic_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_sm_basic_5', to='app.Article')),
                ('slider_sm_basic_6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_sm_basic_6', to='app.Article')),
                ('sm_basic_under_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sm_basic_under_1', to='app.Add')),
                ('sm_basic_under_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sm_basic_under_2', to='app.Article')),
                ('sm_basic_under_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sm_basic_under_3', to='app.Article')),
                ('sm_basic_under_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sm_basic_under_4', to='app.Article')),
                ('sm_basic_under_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sm_basic_under_5', to='app.Add')),
                ('small_article_basic_section_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='small_article_basic_section_1', to='app.Article')),
                ('small_article_basic_section_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='small_article_basic_section_2', to='app.Article')),
                ('small_article_basic_section_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='small_article_basic_section_3', to='app.Article')),
                ('small_article_basic_section_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='small_article_basic_section_4', to='app.Article')),
                ('small_article_basic_section_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='small_article_basic_section_5', to='app.Article')),
                ('small_section_second_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='small_section_second_1', to='app.Article')),
                ('small_section_second_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='small_section_second_2', to='app.Article')),
                ('small_section_second_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='small_section_second_3', to='app.Article')),
                ('small_section_second_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='small_section_second_4', to='app.Add')),
            ],
        ),
    ]
