# Generated by Django 2.2.4 on 2020-09-28 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple_cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='add_navbar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Add'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='basic_center_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basic_center_1', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='basic_center_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basic_center_2', to='app.Add'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='large_basic_under',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='large_basic_under', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='name_1',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='name_2',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='name_3',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='navbar_alert_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navbar_alert_1', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='navbar_alert_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navbar_alert_2', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='navbar_alert_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navbar_alert_3', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='navbar_alert_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navbar_alert_4', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='navbar_alert_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navbar_alert_5', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section_footer_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_footer_1', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section_footer_10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_footer_10', to='app.Add'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section_footer_11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_footer_11', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section_footer_12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_footer_12', to='app.Add'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section_footer_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_footer_2', to='app.Add'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section_footer_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_footer_3', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section_footer_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_footer_4', to='app.Add'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section_footer_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_footer_5', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section_footer_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_footer_6', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section_footer_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_footer_7', to='app.Add'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section_footer_8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_footer_8', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section_footer_9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_footer_9', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section_second_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_second_1', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section_second_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_second_2', to='app.Add'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section_second_left_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_second_left_1', to='app.Add'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section_second_left_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_second_left_2', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section_second_left_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_second_left_3', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section_second_left_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_second_left_4', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section_second_left_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_second_left_5', to='app.Add'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='slider_lg_basic_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slider_lg_basic_1', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='slider_lg_basic_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slider_lg_basic_2', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='slider_lg_basic_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slider_lg_basic_3', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='slider_lg_basic_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slider_lg_basic_4', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='slider_lg_basic_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slider_lg_basic_5', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='slider_lg_basic_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slider_lg_basic_6', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='slider_lg_basic_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slider_lg_basic_7', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='slider_lg_basic_8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slider_lg_basic_8', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='slider_lg_basic_9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slider_lg_basic_9', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='slider_sm_basic_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slider_sm_basic_1', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='slider_sm_basic_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slider_sm_basic_2', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='slider_sm_basic_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slider_sm_basic_3', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='slider_sm_basic_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slider_sm_basic_4', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='slider_sm_basic_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slider_sm_basic_5', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='slider_sm_basic_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slider_sm_basic_6', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='sm_basic_under_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sm_basic_under_1', to='app.Add'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='sm_basic_under_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sm_basic_under_2', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='sm_basic_under_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sm_basic_under_3', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='sm_basic_under_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sm_basic_under_4', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='sm_basic_under_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sm_basic_under_5', to='app.Add'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='small_article_basic_section_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='small_article_basic_section_1', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='small_article_basic_section_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='small_article_basic_section_2', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='small_article_basic_section_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='small_article_basic_section_3', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='small_article_basic_section_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='small_article_basic_section_4', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='small_article_basic_section_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='small_article_basic_section_5', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='small_section_second_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='small_section_second_1', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='small_section_second_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='small_section_second_2', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='small_section_second_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='small_section_second_3', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='small_section_second_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='small_section_second_4', to='app.Add'),
        ),
    ]
