# Generated by Django 2.2.4 on 2020-09-28 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_cms', '0002_auto_20200928_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='slug',
        ),
    ]
