# Generated by Django 2.2.4 on 2020-10-01 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_cms', '0003_remove_homepage_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'ordering': ['-date_published']},
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='name_1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='name_2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='name_3',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='section_footer_row_2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='section_footer_row_3',
        ),
    ]
