# Generated by Django 2.2.4 on 2020-10-02 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200928_1852'),
        ('simple_cms', '0004_auto_20201001_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='small_article_basic_section_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='small_article_basic_section_6', to='app.Article'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='small_article_basic_section_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='small_article_basic_section_7', to='app.Article'),
        ),
    ]
