# Generated by Django 2.2.4 on 2020-10-05 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple_cms', '0005_auto_20201002_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='add_navbar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Article'),
        ),
    ]
