# Generated by Django 2.2.4 on 2020-10-05 11:15

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('simple_cms', '0006_auto_20201005_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='img_tomaszow_tit',
            field=imagekit.models.fields.ProcessedImageField(default=1, upload_to='profile-pictures', verbose_name='Zdjęcie aktualnego wydania'),
            preserve_default=False,
        ),
    ]
