# Generated by Django 2.2.4 on 2020-10-05 11:16

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('simple_cms', '0007_homepage_img_tomaszow_tit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='img_tomaszow_tit',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='profile-pictures', verbose_name='Zdjęcie aktualnego wydania'),
        ),
    ]
