# Generated by Django 2.2.4 on 2020-10-05 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201005_1255'),
        ('simple_cms', '0009_auto_20201005_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='add_navbar_sponsorowane',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='add_navbar_sponsorowane', to='app.Article'),
        ),
    ]
