# Generated by Django 2.2.4 on 2020-10-05 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_cms', '0011_auto_20201005_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='center_section_1',
            new_name='section_1',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='center_section_2',
            new_name='section_2',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='center_section_3',
            new_name='section_3',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='footer_section_1',
            new_name='section_4',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='footer_section_2',
            new_name='section_5',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='footer_section_3',
            new_name='section_6',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='section_first_1',
            new_name='section_7',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='section_first_2',
            new_name='section_8',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='section_first_3',
        ),
    ]
