# Generated by Django 2.2.4 on 2020-09-28 16:52

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tytuł artykułu')),
                ('subtitle', models.TextField(verbose_name='Rozszerzenie tytulu artykulu')),
                ('slug', models.SlugField(unique=True, verbose_name='URL artykułu (zmieniać w ramach konieczności):')),
                ('img', imagekit.models.fields.ProcessedImageField(upload_to='profile-pictures', verbose_name='Zdjęcie (proferowany format 730x450)')),
                ('date_of_publication', models.DateTimeField(verbose_name='Data publikacji')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Treść artykułu')),
                ('premium', models.BooleanField(default=True, verbose_name='Widoczne tylko dla PREMIUM')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Artykuły',
                'verbose_name_plural': 'Artykuły',
            },
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Imię i nazwisko')),
                ('pseudonym', models.CharField(max_length=50, verbose_name='Pseudonim')),
                ('img', imagekit.models.fields.ProcessedImageField(upload_to='profile-pictures', verbose_name='Zdjęcie (proferowany format 400x400)')),
                ('description', models.TextField(null=True, verbose_name='Opis (opcjonalnie)')),
                ('show_img', models.BooleanField(default=False, verbose_name='Pokaż zdjęcie użytkownika')),
            ],
            options={
                'verbose_name': 'Autorzy',
                'verbose_name_plural': 'Autorzy',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nazwa kategorii')),
                ('menu', models.BooleanField(default=False, verbose_name='Pokaż w menu')),
            ],
            options={
                'verbose_name': 'Kategorie artykułów',
                'verbose_name_plural': 'Kategorie artykułów',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Imie lub pseudonim')),
                ('content', models.TextField(verbose_name='Treść dodawanej opinii')),
                ('display', models.BooleanField(default=False, verbose_name='Widoczny komentarz')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.Article', verbose_name='Artykuł')),
            ],
            options={
                'verbose_name': 'Komentarze użytkowników',
                'verbose_name_plural': 'Komentarze użytkowników',
            },
        ),
    ]
