# Generated by Django 2.2.4 on 2020-10-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200928_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='add',
            field=models.BooleanField(default=False, verbose_name='Czy artykuł jest reklamą?'),
        ),
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Adres URL reklamy'),
        ),
    ]
