# Generated by Django 2.2.4 on 2020-10-05 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201005_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='img',
            new_name='img_classic',
        ),
    ]
