# Generated by Django 2.2.4 on 2020-11-17 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_privacypolicy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={'verbose_name': 'Polityka prywatności i regulamin', 'verbose_name_plural': 'Polityka prywatności i regulamin'},
        ),
        migrations.RenameField(
            model_name='privacypolicy',
            old_name='content',
            new_name='privacy',
        ),
    ]
