# Generated by Django 2.2.4 on 2020-11-24 12:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201117_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(max_length=500, unique=True, verbose_name='slug for Category')),
                ('img_url', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='add',
            name='background_img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='add-pictures', verbose_name='background image for Add'),
        ),
        migrations.AddField(
            model_name='add',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description for Add'),
        ),
        migrations.AddField(
            model_name='add',
            name='slug',
            field=models.SlugField(default=1, max_length=500, unique=True, verbose_name='slug for Add'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='add',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='adds', to='app.AddCategory', verbose_name='Category for Add'),
            preserve_default=False,
        ),
    ]
