# Generated by Django 2.2.4 on 2020-10-02 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Konta użytkowników', 'verbose_name_plural': 'Konta użytkowników'},
        ),
    ]
